CREATE TABLE AppSettings (
  UserName varchar(20) NOT NULL,
  State varchar(20) NOT NULL,
  Payload text,
  CreatedDate DATETIME DEFAULT NULL,
  CreatedBy varchar(20) DEFAULT NULL,
  UpdatedDate DATETIME DEFAULT NULL,
  PRIMARY KEY (UserName,State)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

UPDATE User SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE User CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE User DROP COLUMN Id, DROP PRIMARY KEY;
ALTER TABLE User CHANGE COLUMN UserName UserName VARCHAR(250) NOT NULL, ADD PRIMARY KEY (UserName);
ALTER TABLE User CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;

UPDATE ColorMaster SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE ColorMaster CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE ColorMaster CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE ColorMaster CHANGE COLUMN Name Name VARCHAR(255) NULL DEFAULT NULL;

UPDATE ModelMaster SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE ModelMaster CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE ModelMaster CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE ModelMaster CHANGE COLUMN Name Name VARCHAR(255) NULL DEFAULT NULL;

UPDATE ManufactureMaster SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE ManufactureMaster CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE ManufactureMaster CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE ManufactureMaster CHANGE COLUMN Name Name VARCHAR(255) NULL DEFAULT NULL;

UPDATE HandsetMaster SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE HandsetMaster CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE HandsetMaster CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE HandsetMaster CHANGE COLUMN Name Name VARCHAR(255) NULL DEFAULT NULL;

UPDATE Customer SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE Customer CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE Customer CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE Customer CHANGE COLUMN Comments Comments TEXT NULL DEFAULT NULL;

UPDATE Customer_Sales SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE Customer_Sales CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE Customer_Sales CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE Customer_Sales CHANGE COLUMN Comments Comments TEXT NULL DEFAULT NULL;

UPDATE Supplier SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE Supplier CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE Supplier CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE Supplier CHANGE COLUMN Comments Comments TEXT NULL DEFAULT NULL;

UPDATE PhoneStock SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE PhoneStock CHANGE COLUMN SupplyDate InvoiceDate DATETIME NULL DEFAULT NULL;
ALTER TABLE PhoneStock CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE PhoneStock CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE PhoneStock CHANGE COLUMN Comments Comments TEXT NULL DEFAULT NULL;
ALTER TABLE PhoneStock ADD COLUMN InvoiceId INT NULL AFTER Id;

CREATE TABLE Purchase (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `InvoiceNo` VARCHAR(50) NULL,
  `InvoiceDate` DATETIME NOT NULL,
  `SupplierId` INT NULL,
  `Comments` TEXT NULL,
  `IsActive` tinyint(1) NOT NULL,
  `CreatedDate` DATETIME NOT NULL,
  `CreatedBy` VARCHAR(20) NOT NULL,
  `UpdatedDate` DATETIME DEFAULT NULL,
  `UpdatedBy` VARCHAR(20) NULL,
  PRIMARY KEY (`Id`));
INSERT INTO Purchase SELECT Id, '', InvoiceDate, SupplierId, Comments, '1', CreatedDate, CreatedBy, UpdatedDate, UpdatedBy FROM PhoneStock ORDER BY Id;
UPDATE PhoneStock SET InvoiceId = Id;
ALTER TABLE PhoneStock DROP COLUMN `Comments`, DROP COLUMN `InvoiceDate`, DROP COLUMN `SupplierId`;

ALTER TABLE `Invoice` RENAME TO Sales;
UPDATE Sales SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE Sales CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE Sales CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE Sales CHANGE COLUMN Remarks Remarks TEXT NULL DEFAULT NULL, CHANGE COLUMN AccessoriesDesc AccessoriesDesc TEXT NULL DEFAULT NULL;
ALTER TABLE Sales ADD COLUMN BusinessInvoice TINYINT NOT NULL DEFAULT 0 AFTER InvoiceDate;

ALTER TABLE `InvoiceDetails` RENAME TO salesstock;
UPDATE salesstock SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE salesstock CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE salesstock CHANGE COLUMN Item IMEI VARCHAR(50) NULL DEFAULT NULL;
ALTER TABLE salesstock CHANGE COLUMN UnitPrice Cost DOUBLE NULL DEFAULT NULL;
ALTER TABLE salesstock CHANGE COLUMN Description Description TEXT NULL DEFAULT NULL ;
ALTER TABLE salesstock DROP COLUMN IsActive;
ALTER TABLE salesstock DROP COLUMN SalesTax;
ALTER TABLE salesstock ADD COLUMN Returned BOOLEAN DEFAULT false AFTER Discount, ADD COLUMN ReturnedDate DATETIME DEFAULT NULL AFTER Returned;
ALTER TABLE salesstock CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;

CREATE TABLE stock_log (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IMEI` VARCHAR(50) NOT NULL,
  `LogDate` DATETIME NOT NULL,
  `Comments` TEXT NULL,
  `Activity` VARCHAR(45) NOT NULL DEFAULT 'Sold',
  `CreatedDate` datetime NOT NULL,
  `CreatedBy` varchar(250) NOT NULL,
  `UpdatedDate` datetime NOT NULL,
  `UpdatedBy` varchar(250) NOT NULL,
  PRIMARY KEY (`Id`), INDEX (`IMEI` ASC));
INSERT INTO stock_log
(SELECT '', IMEI, UpdatedDate,  '', 'Sold', CreatedDate, CreatedBy, UpdatedDate, UpdatedBy from salesstock Order By CreatedDate)
UNION
(SELECT '', IMEI, UpdatedDate,  '', Status, UpdatedDate, UpdatedBy, UpdatedDate, UpdatedBy FROM phonestock where Status in ('Returned', 'Rejected') Order By UpdatedDate);
UPDATE stock_log SET UpdatedBy = CreatedBy where UpdatedBy = '';

UPDATE AdHocReceipt SET UpdatedDate = CreatedDate WHERE UpdatedDate = 0 OR UpdatedDate = '' OR UpdatedDate IS NULL;
ALTER TABLE AdHocReceipt CHANGE COLUMN Id Id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE AdHocReceipt CHANGE COLUMN CreatedBy CreatedBy VARCHAR(250) NULL DEFAULT NULL, CHANGE COLUMN UpdatedBy UpdatedBy VARCHAR(250) NULL DEFAULT NULL;
ALTER TABLE AdHocReceipt CHANGE COLUMN CreatedDate CreatedDate DATETIME NULL, CHANGE COLUMN UpdatedDate UpdatedDate DATETIME NULL DEFAULT NULL;

DROP TABLE invoicelog;
DROP TABLE outstanding;
DROP TABLE partdetail;
DROP TABLE purchase_sales;
DROP TABLE sysdiagrams;
